version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/convention?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: s3cr3t
      SPRING_JPA_SHOW_SQL: false

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3t
      MYSQL_DATABASE: convention
    ports:
      - "3306:3306"
