version: "3.9"

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/convention
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: s3cr3t
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3t
      MYSQL_DATABASE: convention
      MYSQL_USER: root
      MYSQL_PASSWORD: s3cr3t
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3.8
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
